# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 80, 735, 337))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 12, 2, 1, 1)
        self.btnLoadRef = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLoadRef.setObjectName("btnLoadRef")
        self.gridLayout.addWidget(self.btnLoadRef, 5, 0, 1, 1)
        self.btnShowRef = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnShowRef.setObjectName("btnShowRef")
        self.gridLayout.addWidget(self.btnShowRef, 7, 0, 1, 1)
        self.spinAverage = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinAverage.setMaximum(20)
        self.spinAverage.setObjectName("spinAverage")
        self.gridLayout.addWidget(self.spinAverage, 1, 3, 1, 1)
        self.checkAverage = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkAverage.setObjectName("checkAverage")
        self.gridLayout.addWidget(self.checkAverage, 1, 2, 1, 1)
        self.btnStart = QtWidgets.QPushButton(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 226, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnStart.setPalette(palette)
        self.btnStart.setStyleSheet("background-color: rgb(0, 226, 0);\n"
"color: rgb(0, 0, 0);")
        self.btnStart.setObjectName("btnStart")
        self.gridLayout.addWidget(self.btnStart, 10, 2, 1, 1)
        self.checkSub = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkSub.setObjectName("checkSub")
        self.gridLayout.addWidget(self.checkSub, 8, 0, 1, 1)
        self.spinLower = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinLower.setMaximum(10000)
        self.spinLower.setObjectName("spinLower")
        self.gridLayout.addWidget(self.spinLower, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 0, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnStop.setPalette(palette)
        self.btnStop.setStyleSheet("background-color: rgb(239, 0, 23);\n"
"color: rgb(0, 0, 0);")
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 10, 3, 1, 1)
        self.checkWrite = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkWrite.setObjectName("checkWrite")
        self.gridLayout.addWidget(self.checkWrite, 8, 2, 1, 1)
        self.btnTakeRef = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnTakeRef.setStyleSheet("background-color: rgb(212, 199, 0);\n"
"color: rgb(0, 0, 0);")
        self.btnTakeRef.setObjectName("btnTakeRef")
        self.gridLayout.addWidget(self.btnTakeRef, 10, 0, 1, 1)
        self.btnSaveSpec = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSaveSpec.setStyleSheet("background-color: rgb(79, 145, 255);\n"
"color: rgb(0, 0, 0);")
        self.btnSaveSpec.setObjectName("btnSaveSpec")
        self.gridLayout.addWidget(self.btnSaveSpec, 11, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 12, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 2, 1, 1)
        self.spinInt = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinInt.setMaximum(1000000)
        self.spinInt.setProperty("value", 10000)
        self.spinInt.setObjectName("spinInt")
        self.gridLayout.addWidget(self.spinInt, 5, 3, 1, 1)
        self.spinUpper = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinUpper.setMaximum(10000)
        self.spinUpper.setProperty("value", 1000)
        self.spinUpper.setObjectName("spinUpper")
        self.gridLayout.addWidget(self.spinUpper, 2, 3, 1, 1)
        self.checkWriteAllAve = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkWriteAllAve.setObjectName("checkWriteAllAve")
        self.gridLayout.addWidget(self.checkWriteAllAve, 7, 2, 1, 1)
        self.checkOffset = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkOffset.setObjectName("checkOffset")
        self.gridLayout.addWidget(self.checkOffset, 0, 2, 1, 1)
        self.spinOffset = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinOffset.setDecimals(4)
        self.spinOffset.setMaximum(10000.0)
        self.spinOffset.setObjectName("spinOffset")
        self.gridLayout.addWidget(self.spinOffset, 0, 3, 1, 1)
        self.btnSaveFFT = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSaveFFT.setObjectName("btnSaveFFT")
        self.gridLayout.addWidget(self.btnSaveFFT, 10, 4, 1, 1)
        self.spinFFTupper = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinFFTupper.setMaximum(100000)
        self.spinFFTupper.setProperty("value", 10000)
        self.spinFFTupper.setObjectName("spinFFTupper")
        self.gridLayout.addWidget(self.spinFFTupper, 1, 4, 1, 1)
        self.spinFFTlower = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinFFTlower.setMinimum(-100000)
        self.spinFFTlower.setMaximum(100000)
        self.spinFFTlower.setProperty("value", -10000)
        self.spinFFTlower.setObjectName("spinFFTlower")
        self.gridLayout.addWidget(self.spinFFTlower, 2, 4, 1, 1)
        self.comboWindow = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboWindow.setObjectName("comboWindow")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.gridLayout.addWidget(self.comboWindow, 4, 4, 1, 1)
        self.checkFFT = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkFFT.setChecked(True)
        self.checkFFT.setObjectName("checkFFT")
        self.gridLayout.addWidget(self.checkFFT, 5, 4, 1, 1)
        self.checkFFTAv = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkFFTAv.setObjectName("checkFFTAv")
        self.gridLayout.addWidget(self.checkFFTAv, 7, 4, 1, 1)
        self.checkZeroPad = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkZeroPad.setObjectName("checkZeroPad")
        self.gridLayout.addWidget(self.checkZeroPad, 8, 4, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 12, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 24))
        self.menubar.setObjectName("menubar")
        self.menuSpecra_Viewer = QtWidgets.QMenu(self.menubar)
        self.menuSpecra_Viewer.setStyleSheet("background-color: rgb(71, 70, 72);")
        self.menuSpecra_Viewer.setObjectName("menuSpecra_Viewer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSpecra_Viewer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLoadRef.setText(_translate("MainWindow", "Load Reference from File"))
        self.btnShowRef.setText(_translate("MainWindow", "Show Reference spectra"))
        self.checkAverage.setText(_translate("MainWindow", "Average over:"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.checkSub.setText(_translate("MainWindow", "Substract Reference"))
        self.label_2.setText(_translate("MainWindow", "Spectrum Lowerbound"))
        self.label.setText(_translate("MainWindow", "Spectrum Upperbound"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.checkWrite.setText(_translate("MainWindow", "Write to Files"))
        self.btnTakeRef.setText(_translate("MainWindow", "Take Reference"))
        self.btnSaveSpec.setText(_translate("MainWindow", "Save current Spectra"))
        self.label_4.setText(_translate("MainWindow", "Fileprefix:"))
        self.label_3.setText(_translate("MainWindow", "Integration time"))
        self.checkWriteAllAve.setText(_translate("MainWindow", "Write all Average spectra"))
        self.checkOffset.setText(_translate("MainWindow", "Const. Offset:"))
        self.btnSaveFFT.setText(_translate("MainWindow", "save FFT"))
        self.comboWindow.setItemText(0, _translate("MainWindow", "Blackman"))
        self.comboWindow.setItemText(1, _translate("MainWindow", "Hamming"))
        self.checkFFT.setText(_translate("MainWindow", "Show Fouriertransform"))
        self.checkFFTAv.setText(_translate("MainWindow", "Remove Average b4 FFT"))
        self.checkZeroPad.setText(_translate("MainWindow", "Zero Padding"))
        self.btnExit.setText(_translate("MainWindow", "EXIT"))
        self.menuSpecra_Viewer.setTitle(_translate("MainWindow", "Specra-Viewer"))
